name: emg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - astor=0.7.1
  - blas=1.0=mkl
  - c-ares=1.15.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - click=7.0
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.3
  - joblib=0.13.2
  - jpeg=9b
  - keras-applications=1.0.7
  - keras-preprocessing=1.0.9
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.7.1
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - matplotlib=3.1.0
  - mkl=2019.3
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - mock=3.0.5
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1b
  - pandas=0.24.2
  - pcre=8.43
  - pillow=6.0.0
  - pip=19.1.1
  - pycparser=2.19
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytorch=1.1.0
  - pytz=2019.1
  - qt=5.9.7
  - readline=7.0
  - scikit-learn=0.21.1
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorboardx=1.6
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - tk=8.6.8
  - torchvision=0.3.0
  - tornado=6.0.2
  - tqdm=4.31.1
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - future==0.17.1
    - grpcio==1.21.1
    - markdown==3.1.1
    - protobuf==3.8.0
    - skorch==0.6.0
    - tabulate==0.8.3
    - tb-nightly==1.14.0a20190603
    - werkzeug==0.15.4